/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilKitButton {
    }
    interface StencilKitDiv {
        "children": Array<any>;
    }
    interface StencilKitLink {
    }
}
declare global {
    interface HTMLStencilKitButtonElement extends Components.StencilKitButton, HTMLStencilElement {
    }
    var HTMLStencilKitButtonElement: {
        prototype: HTMLStencilKitButtonElement;
        new (): HTMLStencilKitButtonElement;
    };
    interface HTMLStencilKitDivElement extends Components.StencilKitDiv, HTMLStencilElement {
    }
    var HTMLStencilKitDivElement: {
        prototype: HTMLStencilKitDivElement;
        new (): HTMLStencilKitDivElement;
    };
    interface HTMLStencilKitLinkElement extends Components.StencilKitLink, HTMLStencilElement {
    }
    var HTMLStencilKitLinkElement: {
        prototype: HTMLStencilKitLinkElement;
        new (): HTMLStencilKitLinkElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-kit-button": HTMLStencilKitButtonElement;
        "stencil-kit-div": HTMLStencilKitDivElement;
        "stencil-kit-link": HTMLStencilKitLinkElement;
    }
}
declare namespace LocalJSX {
    interface StencilKitButton {
        "onOnClick"?: (event: CustomEvent<KeyboardEvent>) => void;
    }
    interface StencilKitDiv {
        "children"?: Array<any>;
    }
    interface StencilKitLink {
    }
    interface IntrinsicElements {
        "stencil-kit-button": StencilKitButton;
        "stencil-kit-div": StencilKitDiv;
        "stencil-kit-link": StencilKitLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-kit-button": LocalJSX.StencilKitButton & JSXBase.HTMLAttributes<HTMLStencilKitButtonElement>;
            "stencil-kit-div": LocalJSX.StencilKitDiv & JSXBase.HTMLAttributes<HTMLStencilKitDivElement>;
            "stencil-kit-link": LocalJSX.StencilKitLink & JSXBase.HTMLAttributes<HTMLStencilKitLinkElement>;
        }
    }
}
